### ISSUE TITLE
API Key is now required

### ISSUE THREAD

**Issue by bizzyvinci** [dclimber/python-exchangeratesapi#5]
`api = Api()` would cause `KeyError: 'rates'`.

With a little more finding I discovered that [exchangeratesapi](https://exchangeratesapi.io/documentation/#apikey) now requires API Key. Also it is not absolutely free, it has a [pricing page](https://exchangeratesapi.io/pricing/) and free tier allows 250 requests per month.

A basic request to https://api.exchangeratesapi.io/latest would return
```json
{
    "success": false,
    "error": {
        "code": 101,
        "type": "missing_access_key",
        "info": "You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]"
    }
}
```

Solution: the library should be updated to include API Key.

**Comment by havardl** [comment]
Has this been fixed?

**Comment by bizzyvinci** [comment]
My [fork](https://github.com/bizzyvinci/py-exchangeratesapi) is updated and has issues resolved.
